### ISSUE TITLE
Some Android 11+ devices are experiencing issues after the August security patch update

### ISSUE THREAD

**Issue by NoName1510** [Aliucord/hook#12]
```
Device Manufacturer: INFINIX MOBILITY LIMITED
Device Model
: Infinix X6815B
Android Version : 12
Android SDK
: 31
App VersionName 2.0
App VersionCode :2
**** Crash Head
java.lang.UnsatisfiedLinkError: JNL_ERR returned from JNI OnLoad in "/data/app/~~jhVSK5B6s5FcdaJfQErhgQ==/
com.testCode-TbZh6_46qnRiCdzEml-YAQ==/lib/arm64/
libaliuhook.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1081) at java.lang.Runtime.loadLibrary0(Runtime.java:1003) at java.lang.System.loadLibrary(System.java:1765) at npdcc0.hidden.Hidden0.special_clinit_17_20(Native Method)
at de.roby.android.xposed.XposedBridge.<clinit>(Unknown Source:7)
at
de.robv.android.xposed.XposedHelpers.findAndHookMetho
d(Native Method)
at com.testCode.MainActivity$100000001.onClick(Native Method)
at android.view.View.performClick(View.java:7460)
at android.view.View.performClickInternal(View.java:7433) at android.view.View.access$3700(View.java:840)
at android.view.View$PerformClick.run(View.java:28894) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:241) at android.os.Looper.loop(Looper.java:342)
at
android.app.ActivityThread.main(ActivityThread.java:8118)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.r
un(RuntimeInit.java:583)
at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:104

**Comment by rushiiMachine** [comment]
please provide a full unfiltered logcat

**Comment by NoName1510** [comment]
What do I use to provide error log details, is logfox ok?

**Comment by rushiiMachine** [comment]
`adb logcat -d > log.txt` also works

**Comment by NoName1510** [comment]
[log.txt](https://github.com/user-attachments/files/16901730/log.txt)
This Here is the log of another device with the same error

**Comment by Vendicated** [comment]
from your log, it's because lsplant fails to initialise
```
09-06 08:26:44.031 10956 10956 E LSPlant : Hook Fails: _ZN3art11ClassLinker30ShouldUseInterpreterEntrypointEPNS_9ArtMethodEPKv
09-06 08:26:44.042 10956 10956 E LSPlant : Hook Fails: _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE
09-06 08:26:44.042 10956 10956 E LSPlant : Failed to init jit code cache
09-06 08:26:44.042 10956 10956 E AliuHook: lsplant init failed
```

could you try latest lsplant directly and see if it also happens there? just try running [their tests](https://github.com/LSPosed/LSPlant/tree/master/test)

**Comment by NoName1510** [comment]
Do you have apk available for testing, I don't have laptop to build now until 2 weeks later

**Comment by Juby210** [comment]
Aren't you just using Aliuhook before this commit? 86ec4a086519b98defc5742f2fe503057f354b19
The commit updated lsplant version to fix some compatibility issues. I attached [example](https://github.com/Aliucord/hook/tree/main/example) apk so you can test (it is in the zip).
[example-release.zip](https://github.com/user-attachments/files/16906032/example-release.zip)

**Comment by NoName1510** [comment]
Yes I use the latest update(Got an error so updated and still got the error), the only difference is that I use lsplant-standalone and edit the gadget to build without libc++_shared.so

**Comment by HuynhNgoc2709** [comment]
Same error and what I changed here:

implementation("org.lsposed.lsplant:lsplant-standalone:+")

 arguments += "-DANDROID_STL=c++_static"

**Comment by rushiiMachine** [comment]
@NoName1510 Is this still an issue?

**Comment by NoName1510** [comment]
It still exists if build with above mode https://github.com/Aliucord/hook/issues/12#issuecomment-2366773030

**Comment by rushiiMachine** [comment]
And if not static linking does the issue still occur?

Also could you run the lsplant tests and send a logcat?

**Comment by passself** [comment]
I got the same error in android 15.  The reason for it is lsplant.  Test the lsplant result is the same error : _ZN3art3jit12JitCodeCache19GarbageCollectCacheEPNS_6ThreadE. 

android 15:
readelf -Ws libart64.so| grep JitCodeCache
is:
_ZN3art3jit12JitCodeCache21LookupOsrMethodHeaderEPNS_9ArtMethodE

**Comment by rushiiMachine** [comment]
Related issue: https://github.com/LSPosed/LSPlant/issues/97
This should have fixed it already: https://github.com/LSPosed/LSPlant/commit/0d9faca38da7023fa39fc93383051a04458a3518

@passself Can you give a full logcat of the debug LSPlant test?
